### ISSUE TITLE
esp32 parse SDK

### ISSUE THREAD

**Issue by ABEOmer** [ParsePlatform/Parse-SDK-Arduino#20]
When i am trying to compile the arduino parse SDK example for esp32 board in IDE shows:
WARNING: library Parse-SDK-Arduino-master claims to run on avr, samd, esp8266 architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
In file included from C:\Users\omer\Documents\Arduino\libraries\Parse-SDK-Arduino-master\src/internal/ParseClient.h:28:0,

             from C:\Users\omer\Documents\Arduino\libraries\Parse-SDK-Arduino-master\src/Parse.h:37,

             from C:\Users\omer\Documents\Arduino\sdk\sdk.ino:2:

**Comment by mtrezza** [comment]
Thanks for reporting.

Unfortunately, this project has been retired due to lack of use and contribution. I am closing this issue, but if you want to investigate and fix it, please submit a pull request and we can re-open this issue.

If you are actively using this repository and are interested in helping to continuously maintain it as a contributing member of the Parse Platform Organization, please let us know.

**Comment by garudaonekh** [comment]
Here for ESP32,
https://github.com/garudaonekh/Parse-Platforrm-SDK-for-ESP32

Note: not all features are tested yet
